name: Node.js CI

on: [push]

jobs:
  tests:
    env:
      CI: true

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.3
      - run: |
          sudo apt-get update && sudo apt-get install zopfli brotli
          npm ci
          npm test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          flags: unittests #optional
          name: schema-analyzer #optional
